### ISSUE TITLE
integration testing

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge#1]
This will be a very hard library to test, given all the moving pieces. We will want to read up on [Prefect Testing](https://docs.prefect.io/core/idioms/testing-flows.html).

It may be easier to start with an integration test. Something like this
- Create a synthetic xarray dataset
- Use save_mfdataset to output to netcdf files
- Serve the files over http (optional; could also just use local storage)
- Run the pipeline on the files and produce the zarr dataset
- Open the zarr and assert identical to the original synthetic dataset

Testing the cloud storage parts could be very hard. I think we will just have to use the local filesystem and rely on fsspec abstractions, hoping that things transfer cleanly to different fsspec implementations.

**Comment by TomAugspurger** [comment]
A few more thoughts:

1. It seems like many pipelines will start by fetching many variables and time slices independently. We ask pipeline authors to annotate this somehow, so we can easily test the pipeline on a subset of the data (both during development of the pipeline and as integration tests for pangeo-forge).
2. +1 to relying on fsspec abstractions for testing. We can encourage the use of the `:memory:` filesystem for development and testing.

---

Ideally, we'd be able to take a "real" pipeline and cut it down to a fast-to-run test version by subsetting the amount of data processed and minimizing the cost of IO (by writing to memory).

**Comment by TomAugspurger** [comment]
https://github.com/pangeo-forge/example-pipeline/pull/2/files gives one possible route for testing. The idea there builds off prefect Parameters controlling the extent of the pipeline (what days / what variables are covered).

That defines a new method `Pipeline.get_test_parameters` which transforms the default parameters to ones appropriate for tests (subset of the dates, write to `:memory://` rather than `gcs://`. This does *not* run in our kubernetes environment(s), so stuff relying on that (like writing to gcs) will not work. It's just using GitHub Actions.

**Comment by rabernat** [comment]
The executor tests now exist:

https://github.com/pangeo-forge/pangeo-forge/blob/master/tests/test_executors.py
