### ISSUE TITLE
Non-public source datasets requiring credentials

### ISSUE THREAD

**Issue by scottyhq** [pangeo-forge/pangeo-forge#53]
There are a lot of primary datasets out there that require user authentication before download. E.g. NASA Earthdata Login (https://urs.earthdata.nasa.gov ). I'm curious if pangeo-forge will be limited to public datasets, or if the roadmap includes a mechanism for securely using credentials in recipes? 

I wonder if it's possible for feedstocks to be owned by the creator so that they can add their own credentials as repository secrets for GitHub actions? https://github.com/conda-forge/pangeo-dask-feedstock. On conda-forge we don't have that ability (for example https://github.com/conda-forge/pangeo-dask-feedstock). Maybe @ocefpaf has some ideas on this?

**Comment by rabernat** [comment]
From an API standpoint, how would we like pass the credentials to pangeo forge?

One nice option would be to allow the user to pass in an `input_fs` object as an initialized fsspec filesystem object, e.g. https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.implementations.ftp.FTPFileSystem.

Right now we just open files like this:
https://github.com/pangeo-forge/pangeo-forge/blob/491b04c6135970f551444e041ff2cd85a3dcbe39/pangeo_forge/recipe.py#L49-L50

If we had a fsspec object for the inputs, it would be easy to use that here instead of the generic fsspec.open (which determines the class to use by examining the URL).

**Comment by davidbrochart** [comment]
It seems that we can also pass username and password to the generic `fsspec.open` in the `kwargs` (see https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.open).
