### ISSUE TITLE
GPM IMERG recipe issues

### ISSUE THREAD

**Issue by davidbrochart** [pangeo-forge/pangeo-forge#56]
In https://github.com/pangeo-forge/staged-recipes/issues/5 we get one HDF5 file per half hour, which has several fields, all on the same lat/lon grid, but with different data types (some in `float32` and some in `int16`). This means that we want to concatenate some of them along the time dimension in chunks of 4 half-hours, and others in chunks of 8 half-hours, to get the 100MB chunk size.
I believe the `NetCDFtoZarrSequentialRecipe` recipe doesn't support heterogeneous data types yet, am I right? If that is true, would it make sense to implement `inputs_per_chunk` as a dictionary of the form `name: inputs_per_chunk`?
We need to authenticate to the HTTP server with a HTTP user and password. Is it implemented in the `NetCDFtoZarrSequentialRecipe` recipe? May be related to #53.

**Comment by rabernat** [comment]
> This means that we want to concatenate some of them along the time dimension in chunks of 4 half-hours, and others in chunks of 8 half-hours, to get the 100MB chunk size.

Yes, if you want to insist on having constant-memory chunks, then you would want to do this. In my experience, it's best to have the different variables in a dataset all have the same chunk size in terms of dimensions. Otherwise you have to do some rechunking if you want to do calculations on multiple variables. Having some chunks be 50MB, others 100MB is really not a problem IMO.

Nevertheless, it would be good to have the ability to customize chunks more. That is also discussed in #50.

xref #53 for credentials

**Comment by rabernat** [comment]
> I believe the `NetCDFtoZarrSequentialRecipe` recipe doesn't support heterogeneous data types yet, am I right?

Just to clarify, it does support heterogeneous data types. ✅
